### ISSUE TITLE
sonic-ci-helper

### ISSUE THREAD

**Issue by ZhouYixun** [jenkins-infra/repository-permissions-updater#2624]
### Repository URL

https://github.com/SonicCloudOrg/sonic-ci-helper

### New Repository Name

sonic-ci-helper-plugin

### Description

This plugin help your CI/CD with Sonic Testing Platform.

### GitHub users to have commit permission

@ZhouYixun

### Jenkins project users to have release permission

zhouyixun

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by ZhouYixun** [comment]
> cc @Wadeck

Thx!

**Comment by Kevin-CB** [comment]
Quick look at the code, we will need a more deeper audit.
Tracked internally as JENSEC-1848 where we will confirm the stuff and find others potentially.

**Comment by ZhouYixun** [comment]
> Quick look at the code, we will need a more deeper audit. Tracked internally as JENSEC-1848 where we will confirm the stuff and find others potentially.

What should I do?

**Comment by timja** [comment]
Wait till the security team do their audit

**Comment by ZhouYixun** [comment]
> Wait till the security team do their audit

Ok，Thx

**Comment by ValdesChe** [comment]
Hey @ZhouYixun ,

We were able to perform a deeper audit and here's some feedback for you:

Path traversal : User with job/Configure permission could access files and directories that are stored outside the WORKSPACE.
-  [utils/HttpUtils.java#L70](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/d02c6e0a1feee328d35bbb09201e1a8cb6a7caea/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L70)
-  [utils/HttpUtils.java#L223](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/d02c6e0a1feee328d35bbb09201e1a8cb6a7caea/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L223)
-  [utils/HttpUtils.java#L250](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/d02c6e0a1feee328d35bbb09201e1a8cb6a7caea/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L250)

Recommendation: Use hudson.FilePath instead of File. Refer to https://javadoc.jenkins.io/hudson/FilePath.html for details. 

Please address our findings and ping us when you're done or if you have any questions.

**Comment by ZhouYixun** [comment]
@timja What should I do now?

**Comment by timja** [comment]
Wait for the security team to check again

**Comment by ValdesChe** [comment]
@ZhouYixun, the fix you provided is not effective.  You will need to explicitly check whether the provided path does not attempt to escape directory (i.e. does not contain ../../ )

**Comment by ZhouYixun** [comment]
> @ZhouYixun，您提供的修复无效。您需要明确检查提供的路径是否不尝试转义目录（即不包含 ../../ ）

ok, I will fix it quickly

**Comment by ZhouYixun** [comment]
> @ZhouYixun, the fix you provided is not effective. You will need to explicitly check whether the provided path does not attempt to escape directory (i.e. does not contain ../../ )

fixed, please check it again!

**Comment by ValdesChe** [comment]
Thank you @ZhouYixun for you quick response,
The fix you provided is still not effective. The reason been that you are mixing `FilePath` and `File` usage.
I will recommend you to : 

- [HttpUtils.java#L63](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/e5c8b7b83c13422db8d599e7619dffba820fe56e/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L63) => Checking for ".." in paramBean.getScanDir() string

- [HttpUtils.java#L71](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/e5c8b7b83c13422db8d599e7619dffba820fe56e/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L71) => Make sure path variable has job workspace as an ancestor
- [HttpUtils.java#L258-L260](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/3a38ff41732e01b84397cdbc6e216cf3ea1ba447/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L258-L260) use `FilePath`
- [HttpUtils.java#L71](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/e5c8b7b83c13422db8d599e7619dffba820fe56e/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L71) use FilePath since the `path `variable content is from agent file which is not trusted by default.

Please let us know if you have any question.

**Comment by yaming116** [comment]
@ValdesChe 
- [HttpUtils.java#L63](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/e5c8b7b83c13422db8d599e7619dffba820fe56e/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L63) => Checking for ".." in paramBean.getScanDir() string
  - i see FilePaht will check ".." and remove it
- [HttpUtils.java#L258-L260](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/3a38ff41732e01b84397cdbc6e216cf3ea1ba447/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L258-L260) use FilePath
  - this can fix
-  [HttpUtils.java#L71](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/e5c8b7b83c13422db8d599e7619dffba820fe56e/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L71)
  -  Here I need to upload a file, FilePath does not conform to the parameter type

**Comment by ZhouYixun** [comment]
@ValdesChe You can review again. Thx!

**Comment by yaming116** [comment]
> I don't think there is a related issue here, the `path` variable is obtained from FilePath.
Since I'm not sure about the user's final file size, I don't think it's a good idea to create a temporary file if the user's file is too large.
Is there something that might not be modified here because I found that the final FilePath also reads the file content the same way?

**Comment by yaming116** [comment]
> @ZhouYixun @yaming116 You will still have a problem with this fix due to [HttpUtils.java#L71](https://github.com/SonicCloudOrg/sonic-ci-helper/blob/0799652943ddb88be4a6694ab37aeee836265c55/src/main/java/io/jenkins/plugins/sonic/utils/HttpUtils.java#L71). Because if for some reason your `path` exists on controller, it will result in arbitrary file read from controller.
> 
> A simple solution will be :
> 
> 1. read the file content using `FilePath#readToString()` for example,
> 2. create a temporary file on the controller File#createTempFile
> 3. read that file from the controller and use in the `uploadAction` function.
> 
> Here is a snippet of code to fix the issue : `
> 
> ```
>     final String fileContent = paramBean.getWorkspace().child(path).readToString();
> 
>     final File tempFile = File.createTempFile("uploadstep", "tmp");
>     try (Writer w = new BufferedWriter(new FileWriter(tempFile))) {
>         w.write(fileContent);
>     }
>     // upload temp file from controller here
>     String url = uploadAction(build, tempFile, listener, paramBean);
> ```
> 
> `

I don't think there is a related issue here, the path variable is obtained from FilePath.
Since I'm not sure about the user's final file size, I don't think it's a good idea to create a temporary file if the user's file is too large.
Is there something that might not be modified here because I found that the final FilePath also reads the file content the same way?

**Comment by daniel-beck** [comment]
> I don't think there is a related issue here, the path variable is obtained from FilePath.

You obtain the path from the agent, but upload whatever file is at that location from the controller file system. If they're on different systems, this will generally fail anyway. Try your code with the agent or controller running inside a container, and the other outside, and see what happens.

Either you copy the file from the agent to the controller (as described in Valdes's suggestion), or you perform the upload from the agent directly, which involves defining your own https://javadoc.jenkins.io/jenkins/security/MasterToSlaveCallable.html / https://javadoc.jenkins.io/jenkins/MasterToSlaveFileCallable.html, which is more difficult (especially to troubleshoot when things go wrong).

**Comment by ZhouYixun** [comment]
@ValdesChe @daniel-beck  You can review again. Thx!

**Comment by yaming116** [comment]
@ValdesChe All dependencies are completely open source, with one currently published in jitpack.io

**Comment by ValdesChe** [comment]
@yaming116 @ZhouYixun  you forgot to add jipack.io in your POM repositories. 


```
<repositories>
        .....
        <repository>
            <id>jitpack.io</id>
            <url>https://www.jitpack.io</url>
        </repository>
</repositories>
```
Please make the changes so we can move to the next step. 
I have checked the fix with repository changes and it's effective.

**Comment by yaming116** [comment]
@ValdesChe done

**Comment by ZhouYixun** [comment]
> @yaming116 @ZhouYixun 您忘记在您的 POM 存储库中添加 jipack.io。
> 
> ```
> <repositories>
>         .....
>         <repository>
>             <id>jitpack.io</id>
>             <url>https://www.jitpack.io</url>
>         </repository>
> </repositories>
> ```
> 
> 请进行更改，以便我们可以进行下一步。 我已经检查了存储库更改的修复，它是有效的。

we fixed , please check again! thx!

**Comment by ValdesChe** [comment]
@ZhouYixun @yaming116 the fix looks good for me. The hosting process can be continued.

**Comment by ZhouYixun** [comment]
> @ZhouYixun @yaming116 the fix looks good for me. The hosting process can be continued.

What should we do in next part?

**Comment by ValdesChe** [comment]
> What should we do in next part?

You have nothing to do. We will reach out to you very soon.

**Comment by timja** [comment]
Hi

It looks like you undid some fixes at some point, please fix the issues the bot is reporting

**Comment by yaming116** [comment]
> Hi
> 
> It looks like you undid some fixes at some point, please fix the issues the bot is reporting

ok,we will fix soon

**Comment by ZhouYixun** [comment]
@timja sorry, I forget jira password, what should I do?

**Comment by timja** [comment]
> @timja sorry, I forget jira password, what should I do?

https://accounts.jenkins.io/passwordReset
